server:
  #端口
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.134.190.143:3306/yeb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: yeb
    password: yeb

    hikari:

      pool-name: DateHikariCP

      minimum-idle: 5

      idle-timeout: 180000

      maximum-pool-size: 10

      auto-commit: true

      max-lifetime: 1800000

      connection-timeout: 30000

      connection-test-query: SELECT 1

  redis:

    timeout: 10000ms

    host: localhost

    port: 6379

    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  rabbitmq:
    username: guest
    password: guest
    host: 43.134.190.143
    port: 5672
    publisher-confirm-type: correlated
    publisher-returns: true


  main:
    allow-circular-references: true


mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: com.wesley.server.pojo
  configuration:
    map-underscore-to-camel-case: false

logging:
  level:
    com.wesley.server.mapper: debug

jwt:
  tokenHeader: Authorization
  secret: yeb-secret
  expiration: 604800
  tokenHead: Bearer
