server:
  port: 8082
spring:
  mail:
    host: smtp.163.com
    protocol: smtp
    default-encoding: utf-8
    #export MAIL_PASSWORD=yourActualPassword
    password: ${MAIL_PASSWORD}
    username: wesleywei1@163.com
    port: 25

  # rabbitmq config
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual

  main:
    allow-bean-definition-overriding: true

  redis:
    timeout: 10000ms
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 1024
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5